# Generated by Django 5.2.6 on 2026-10-07 20:52

import django.db.models.deletion
import venues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('google_reviews_url', models.URLField(blank=True)),
                ('agreement_signed_on', models.DateField(blank=True, help_text='Date the placement agreement was signed. No agreement, no stickers: print sheets are refused until this is set.', null=True)),
                ('active', models.BooleanField(default=True)),
                ('board_token', models.CharField(default=venues.models.new_board_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Where it is, e.g. "Men\'s stall 2".', max_length=80)),
                ('product', models.CharField(choices=[('large', 'Big Splash (large sticker)'), ('branded', 'Branded sticker (graphic + URL)'), ('urinal_target', 'Bullseye urinal target')], default='large', max_length=20)),
                ('code', models.CharField(default=venues.models.new_short_code, editable=False, max_length=12, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='venues.venue')),
            ],
            options={
                'ordering': ['venue__name', 'label'],
            },
        ),
    ]
