# Generated by Django 5.2.6 on 2026-10-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='allow_political_ads',
            field=models.BooleanField(default=False, help_text="Off by default: the venue's name sits next to every ad, so it opts in."),
        ),
    ]
