# Generated by Django 5.2.6 on 2026-10-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='show_on_leaderboard',
            field=models.BooleanField(default=False, help_text='Opt-in: list this venue on the public cleanest-bathrooms page.'),
        ),
    ]
