# Generated by Django 5.2.6 on 2026-10-08 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_show_on_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('text_sha256', models.CharField(max_length=64)),
                ('signer_name', models.CharField(max_length=120)),
                ('signer_title', models.CharField(max_length=120)),
                ('signer_email', models.EmailField(max_length=254)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='venues.venue')),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='SamplePackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested (verify the signer)'), ('verified', 'Verified'), ('printed', 'Printed'), ('shipped', 'Shipped')], default='requested', max_length=10)),
                ('ship_to_name', models.CharField(max_length=120)),
                ('ship_to_address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('tracking_number', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_packs', to='venues.venue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
