# Generated by Django 5.2.6 on 2026-10-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push (ntfy)')], max_length=10)),
                ('target', models.CharField(help_text='Email address or ntfy topic.', max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('ok', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
