# Generated by Django 5.2.6 on 2026-10-07 20:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('no_tp', 'Out of toilet paper'), ('no_soap', 'Out of soap'), ('no_towels', 'No paper towels / dryer broken'), ('clog', 'Clogged or overflowing'), ('spill', 'Wet floor / mess'), ('broken', "Something's broken (lock, flush, light)"), ('other', 'Something else')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('open', 'Open'), ('ack', 'On it'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='venues.placement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=280)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='venues.placement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
