# Generated by Django 5.2.6 on 2026-10-07 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=80)),
                ('body', models.CharField(blank=True, max_length=200)),
                ('cta_label', models.CharField(default='Check it out', max_length=30)),
                ('target_url', models.URLField()),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('weight', models.PositiveSmallIntegerField(default=1, help_text='Relative share of impressions among live campaigns.')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['advertiser', 'headline'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visitor_hash', models.CharField(max_length=64)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to='venues.placement')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='ads.campaign')),
            ],
        ),
    ]
