# Generated by Django 5.2.6 on 2026-10-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Political ads: made in whole or substantially with AI (Michigan requires a disclosure).'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='approved_target_url',
            field=models.URLField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('local_business', 'Local business'), ('food', 'Food & non-alcoholic drink'), ('services', 'Services & trades'), ('events', 'Events & entertainment'), ('retail', 'Retail'), ('wellness', 'Health & wellness (no medical claims)'), ('nonprofit', 'Nonprofit & public service'), ('political', 'Political')], default='local_business', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='paid_for_by',
            field=models.CharField(blank=True, help_text='Political ads: the full disclaimer, shown verbatim.', max_length=300),
        ),
        migrations.AddField(
            model_name='campaign',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sponsor_contact',
            field=models.CharField(blank=True, help_text='Political ads: sponsor address or website.', max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
