# Generated by Django 5.2.6 on 2026-10-07 21:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenuePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month.', unique=True)),
                ('gross_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_cut', models.DecimalField(decimal_places=3, default=Decimal('0.100'), help_text='0.100 = 10%.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('closed', models.BooleanField(default=False, help_text='Tick once paid out; the report is then for the record.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('is_bot', models.BooleanField(default=False)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='venues.placement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
