# Generated by Django 5.2.6 on 2026-10-07 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_campaign_ai_generated_campaign_approved_target_url_and_more'),
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impressions', to='ads.campaign'),
        ),
    ]
